export const column: string;
export const row: string;
export const tile: string;
export const tileW1: string;
export const tileW2: string;
export const tileH3: string;
export const tileAuto: string;
export const tileFrosted: string;
export const transparent: string;
